version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH python -m pip install uv
    post_install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --no-install-project --extra files --group mddocs
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m pip list -v
    pre_build:
      - python mddocs/scripts/generate_anchors.py
      - python mddocs/scripts/fix_refs.py
      - python mddocs/scripts/links2anchors.py
    build:
      - PYTHONPATH=$READTHEDOCS_REPOSITORY_PATH cd mddocs && mkdocs build
      - mkdir -p $READTHEDOCS_OUTPUT/html
      - cp -r mddocs/generated/* $READTHEDOCS_OUTPUT/html/
