version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH python -m pip install uv
      # remove after https://github.com/zqmillet/sphinx-plantuml/pull/4
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv pip install --no-cache-dir --no-deps sphinx-plantuml
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv pip install --no-cache-dir .[ftp,ftps,hdfs,samba,s3,sftp,webdav,spark] -r requirements/docs.txt
    post_install:
      # TODO: remove after upgrading autodoc-pydantic to v2
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv pip install --no-cache-dir "sphinx<8"
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m pip list -v

# TODO: uncomment after https://github.com/zqmillet/sphinx-plantuml/pull/4
#python:
#  install:
#  - requirements: requirements/docs.txt
#  - method: pip
#    path: .
#    extra_requirements:
#    - ftp
#    - ftps
#    - hdfs
#    - samba
#    - s3
#    - sftp
#    - webdav
#    - spark
