site_name: onETL Docs
docs_dir: docs                             # Where to find the English markdown files
site_dir: generated                        # Where to put the English HTML files

theme:
  name: material
  # custom_dir: '../../overrides/'                    # This is where the customization of the theme lives
  logo: _static/images/logo.svg                      # The logo is shared by all languages
  favicon: _static/images/icon.svg                   # The favicon is shared by all languages
  language: en
  features:
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml

extra_css:
  - _static/stylesheets/autodoc_pydantic.css         # CSS is shared by all languages

extra_javascript:
  - _static/javascripts/mermaid_zoom.js

extra:                                              # Language Selection
  onetl_logo_wide: '[![onETL logo](_static/images/logo_wide.svg)](https://github.com/MTSWebServices/onetl)'
  repo_status_badge: '[![Repo status - Active](https://www.repostatus.org/badges/latest/active.svg)](https://github.com/MTSWebServices/onetl)'
  pypi_release_bage: '[![PyPI - Latest Release](https://img.shields.io/pypi/v/onetl)](https://pypi.org/project/onetl/)'
  pypi_license_bage: '[![PyPI - License](https://img.shields.io/pypi/l/onetl.svg)](https://github.com/MTSWebServices/onetl/blob/develop/LICENSE.txt)'
  pypi_pyversion_bage: '[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/onetl.svg)](https://pypi.org/project/onetl/)'
  pypi_downloads_bage: '[![PyPI - Downloads](https://img.shields.io/pypi/dm/onetl)](https://pypi.org/project/onetl/)'
  docs_status_badge: '[![Documentation - ReadTheDocs](https://readthedocs.org/projects/onetl/badge/?version=stable)](https://onetl.readthedocs.io/)'
  ci_status_badge: '[![Github Actions - latest CI build status](https://github.com/MTSWebServices/onetl/workflows/Tests/badge.svg)](https://github.com/MTSWebServices/onetl/actions)'
  precommit_badge: '[![pre-commit.ci Status](https://results.pre-commit.ci/badge/github/MTSWebServices/onetl/develop.svg)](https://results.pre-commit.ci/latest/github/MTSWebServices/onetl/develop)'
  test_cov_badge: '[![Test coverage - percent](https://codecov.io/gh/MTSWebServices/onetl/branch/develop/graph/badge.svg?token=RIO8URKNZJ)](https://codecov.io/gh/MTSWebServices/onetl)'
  etl_entities_link: '[`etl-entities`](https://github.com/MTSWebServices/etl-entities)'
  support_hooks: '[![support hooks](https://img.shields.io/badge/%20-support%20hooks-blue)](hooks/index.md)'

plugins:
  - autorefs
  - literate-nav:
      nav_file: nav.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            show_source: false
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            heading_level: 3
            docstring_style: numpy
            docstring_section_style: list
            extensions:
              - scripts/griffe_expand_refs.py:ExpandShortRefs
              - griffe_inherited_docstrings
            # - griffe_sphinx
            # - griffe_pydantic: {schema: false}
  - macros
  # - plantuml:
  #     puml_url: https://www.plantuml.com/plantuml/
  #     puml_keyword: plantuml
  # - i18n:
  #     docs_structure: folder
  #     languages:
  #       - locale: en
  #         default: true
  #         name: English
  #         build: true
  #       - locale: ru
  #         name: Русский
  #         build: false

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
