name: Tests for MSSQL
on:
  workflow_call:
    inputs:
      mssql-version:
        required: true
        type: string
      spark-version:
        required: true
        type: string
      pydantic-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-mssql:
    name: Run MSSQL tests (server=${{ inputs.mssql-version }}, spark=${{ inputs.spark-version }}, pydantic=${{ inputs.pydantic-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start MSSQL
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile mssql pull
          docker compose --profile mssql up -d --wait --wait-timeout 200
        env:
          MSSQL_IMAGE: mcr.microsoft.com/mssql/server:${{ inputs.mssql-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      # https://github.com/pymssql/pymssql/issues/372#issuecomment-742386160
      - name: Add missing sqlfont.h file
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends freetds-dev libkrb5-dev gcc

      - name: Cache Ivy
        uses: actions/cache@v5
        if: inputs.with-cache
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy-spark${{ inputs.spark-version }}-pydantic${{ inputs.pydantic-version }}-mssql-${{ hashFiles('onetl/connection/db_connection/*.py', 'onetl/connection/file_df_connection/*.py') }}
          restore-keys: |
            ${{ runner.os }}-ivy-spark${{ inputs.spark-version }}-pydantic${{ inputs.pydantic-version }}-mssql-${{ hashFiles('onetl/connection/db_connection/*.py', 'onetl/connection/file_df_connection/*.py') }}
            ${{ runner.os }}-ivy-spark${{ inputs.spark-version }}-pydantic${{ inputs.pydantic-version }}-mssql-

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
          enable-cache: "false"

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-

      - name: Install dependencies
        run: |
          uv sync \
            --no-install-project \
            --group test \
            --group test-mssql \
            --group test-spark-${{ inputs.spark-version }} \
            --group test-pydantic-${{ inputs.pydantic-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          source .env.local
          ./pytest_runner.sh -m mssql

      - name: Dump MSSQL logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: mcr.microsoft.com/mssql/server
          dest: ./logs

      - name: Upload MSSQL logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: container-logs-mssql-${{ inputs.mssql-version }}-spark${{ inputs.spark-version }}-python-${{ inputs.python-version }}-os-${{ inputs.os }}
          path: logs/*

      - name: Shutdown MSSQL
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-mssql-${{ inputs.mssql-version }}-spark${{ inputs.spark-version }}-python-${{ inputs.python-version }}-os-${{ inputs.os }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
