name: Tests for FTP
on:
  workflow_call:
    inputs:
      ftp-version:
        required: true
        type: string
      pydantic-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-ftp:
    name: Run FTP tests (server=${{ inputs.ftp-version }}, pydantic=${{ inputs.pydantic-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start FTP
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile ftp pull
          docker compose --profile ftp up -d --wait --wait-timeout 200
        env:
          FTP_IMAGE: chonjay21/ftps:${{ inputs.ftp-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
          cache-suffix: tests-ftp-pydantic-${{ inputs.pydantic-version }}

      - name: Install dependencies
        run: |
          uv sync \
            --no-install-project \
            --extra ftp \
            --group test \
            --group test-pydantic-${{ inputs.pydantic-version }}

      - name: Run tests
        run: |
          mkdir reports/ || echo "Directory exists"
          source .env.local
          ./pytest_runner.sh -m ftp

      - name: Dump FTP logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: chonjay21/ftps
          dest: ./logs

      - name: Upload FTP logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: container-logs-ftp-${{ inputs.ftp-version }}-python-${{ inputs.python-version }}-os-${{ inputs.os }}
          path: logs/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true

      - name: Shutdown FTP
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-ftp-${{ inputs.ftp-version }}-python-${{ inputs.python-version }}-os-${{ inputs.os }}
          path: reports/*
