name: Tests for Oracle
on:
  workflow_call:
    inputs:
      oracle-image:
        required: true
        type: string
      oracle-version:
        required: true
        type: string
      db-name:
        required: false
        type: string
        default: FREEPDB1
      spark-version:
        required: true
        type: string
      pydantic-version:
        required: true
        type: string
      java-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      with-cache:
        required: false
        type: boolean
        default: true

jobs:
  test-oracle:
    name: Run Oracle tests (server=${{ inputs.oracle-version }}, spark=${{ inputs.spark-version }}, pydantic=${{ inputs.pydantic-version }}, java=${{ inputs.java-version }}, python=${{ inputs.python-version }}, os=${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Oracle
        run: |
          docker compose --profile all down -v --remove-orphans
          docker compose --profile oracle pull
          docker compose --profile oracle up -d --wait --wait-timeout 200
        env:
          ORACLE_IMAGE: ${{ inputs.oracle-image }}:${{ inputs.oracle-version }}

      - name: Set up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache Ivy
        uses: actions/cache@v5
        if: inputs.with-cache
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy-spark${{ inputs.spark-version }}-oracle-${{ hashFiles('onetl/connection/db_connection/*.py', 'onetl/connection/file_df_connection/*.py') }}
          restore-keys: |
            ${{ runner.os }}-ivy-spark${{ inputs.spark-version }}-oracle-${{ hashFiles('onetl/connection/db_connection/*.py', 'onetl/connection/file_df_connection/*.py') }}
            ${{ runner.os }}-ivy-spark${{ inputs.spark-version }}-oracle-

      - name: Set up Oracle instantclient
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libaio1 || sudo apt-get install --no-install-recommends libaio1t64
          [ -f "/usr/lib/x86_64-linux-gnu/libaio.so.1t64" ] && sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
          mkdir ./tmp
          wget -P ./tmp https://download.oracle.com/otn_software/linux/instantclient/2110000/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip
          mkdir -p ./oracle
          unzip ./tmp/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip -d ./oracle
          rm -rf ./tmp/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
          enable-cache: "false"

      # astral-sh/setup-uv cannot restore multiple keys
      - name: Cache uv
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-spark${{ inputs.spark-version }}-${{ hashFiles('uv.lock') }}
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-spark${{ inputs.spark-version }}-
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-pydantic${{ inputs.pydantic-version }}-
            ${{ runner.os }}-python${{ env.DEFAULT_PYTHON }}-

      - name: Install dependencies
        run: |
          uv sync \
            --no-install-project \
            --group test \
            --group test-oracle \
            --group test-spark-${{ inputs.spark-version }} \
            --group test-pydantic-${{ inputs.pydantic-version }}

      - name: Run tests
        run: |
          export ONETL_ORA_CLIENT_PATH=./oracle/instantclient_21_10
          export LD_LIBRARY_PATH=${ONETL_ORA_CLIENT_PATH}:${LD_LIBRARY_PATH}
          export PATH=${ONETL_ORA_CLIENT_PATH}:${PATH}

          mkdir reports/ || echo "Directory exists"
          source .env.local
          export "ONETL_ORA_SERVICE_NAME=${{ inputs.db-name }}"
          ./pytest_runner.sh -m oracle

      - name: Dump Oracle logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: ${{ inputs.oracle-image }}
          dest: ./logs

      - name: Upload Oracle logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: container-logs-oracle-${{ inputs.oracle-version }}-spark${{ inputs.spark-version }}-python-${{ inputs.python-version }}-os-${{ inputs.os }}
          path: logs/*

      - name: Shutdown Oracle
        if: always()
        run: |
          docker compose --profile all down -v --remove-orphans

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-oracle-${{ inputs.oracle-version }}-spark${{ inputs.spark-version }}-python-${{ inputs.python-version }}-os-${{ inputs.os }}
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
